CREATE DATABASE MAXI
go
USE [MAXI]
GO
/****** Object:  Table [dbo].[BENEFICIARY]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BENEFICIARY](
	[BENEFICIARYID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEEID] [int] NOT NULL,
	[FIRSTNAME] [varchar](100) NOT NULL,
	[LASTNAME] [varchar](100) NOT NULL,
	[DATEOFBIRTH] [datetime] NOT NULL,
	[CURP] [varchar](18) NOT NULL,
	[SSN] [varchar](11) NOT NULL,
	[PHONENUMBER] [varchar](10) NOT NULL,
	[NATIONALITY] [varchar](50) NOT NULL,
	[PARTICIPATIONPERCENTAGE] [int] NOT NULL,
	[ISDELETED] [bit] NOT NULL,
 CONSTRAINT [PK_BENEFICIARY] PRIMARY KEY CLUSTERED 
(
	[BENEFICIARYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEEID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [varchar](100) NOT NULL,
	[LASTNAME] [varchar](100) NOT NULL,
	[DATEOFBIRTH] [datetime] NOT NULL,
	[EMPLOYEENUMBER] [int] NOT NULL,
	[CURP] [varchar](18) NOT NULL,
	[SSN] [varchar](11) NOT NULL,
	[PHONENUMBER] [varchar](10) NOT NULL,
	[NATIONALITY] [varchar](50) NOT NULL,
	[ISDELETED] [bit] NOT NULL,
 CONSTRAINT [PK_EMPLOYE] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BENEFICIARY] ADD  CONSTRAINT [DF_BENEFICIARY_ISDELETED]  DEFAULT ((0)) FOR [ISDELETED]
GO
ALTER TABLE [dbo].[EMPLOYEE] ADD  DEFAULT ((0)) FOR [ISDELETED]
GO
ALTER TABLE [dbo].[BENEFICIARY]  WITH CHECK ADD  CONSTRAINT [FK_BENEFICIARY_EMPLOYEE] FOREIGN KEY([EMPLOYEEID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEEID])
GO
ALTER TABLE [dbo].[BENEFICIARY] CHECK CONSTRAINT [FK_BENEFICIARY_EMPLOYEE]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_EMPLOYEE] FOREIGN KEY([EMPLOYEEID])
REFERENCES [dbo].[EMPLOYEE] ([EMPLOYEEID])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_EMPLOYEE]
GO
/****** Object:  StoredProcedure [dbo].[SPR_ADDBENEFICIARY]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	ADD BENEFICIARY
-- =============================================
CREATE PROCEDURE [dbo].[SPR_ADDBENEFICIARY]
(
	@FIRSTNAME NVARCHAR(100) ,
	@LASTNAME NVARCHAR(100) ,
	@DATEOFBIRTH DATETIME,
	@EMPLOYEEID INT,
	@CURP NVARCHAR(18),
	@SSN NVARCHAR(11) ,
	@PHONENUMBER NVARCHAR(10) ,
	@NATIONALITY NVARCHAR(50),
	@PARTICIPATIONPERCENTAGE INT
)
AS          
SET NOCOUNT ON
BEGIN
	DECLARE @BENEFICIARYID AS INT 
	INSERT INTO BENEFICIARY ([FIRSTNAME],[LASTNAME],[DATEOFBIRTH],[EMPLOYEEID],[CURP],[SSN],[PHONENUMBER],[NATIONALITY],[PARTICIPATIONPERCENTAGE]) 
	VALUES(@FIRSTNAME,@LASTNAME,@DATEOFBIRTH,@EMPLOYEEID,@CURP,@SSN,@PHONENUMBER,@NATIONALITY,@PARTICIPATIONPERCENTAGE)
	SELECT @BENEFICIARYID = @@IDENTITY
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) WHERE BENEFICIARYID = @BENEFICIARYID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_ADDEMPLOYEE]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	ADD EMPLOYEE
-- =============================================
CREATE PROCEDURE [dbo].[SPR_ADDEMPLOYEE]
(
	@FIRSTNAME NVARCHAR(100) ,
	@LASTNAME NVARCHAR(100) ,
	@DATEOFBIRTH DATETIME,
	@EMPLOYEENUMBER INT,
	@CURP NVARCHAR(18),
	@SSN NVARCHAR(11) ,
	@PHONENUMBER NVARCHAR(10) ,
	@NATIONALITY NVARCHAR(50)
)
AS          
SET NOCOUNT ON
BEGIN
	DECLARE @EMPLOYEEID AS INT 
	INSERT INTO EMPLOYEE ([FIRSTNAME],[LASTNAME],[DATEOFBIRTH],[EMPLOYEENUMBER],[CURP],[SSN],[PHONENUMBER],[NATIONALITY]) 
	VALUES(@FIRSTNAME,@LASTNAME,@DATEOFBIRTH,@EMPLOYEENUMBER,@CURP,@SSN,@PHONENUMBER,@NATIONALITY)
	SELECT @EMPLOYEEID = @@IDENTITY
	SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEENUMBER, CURP, SSN, PHONENUMBER, NATIONALITY, ISDELETED FROM EMPLOYEE WITH(NOLOCK) WHERE EMPLOYEEID = @EMPLOYEEID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_DELETEBENEFICIARY]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	DELETE BENEFICIARY
-- =============================================
CREATE PROCEDURE [dbo].[SPR_DELETEBENEFICIARY]
(
	@BENEFICIARYID INT
)
AS          
SET NOCOUNT ON
BEGIN
	UPDATE BENEFICIARY SET [ISDELETED] = 1 WHERE BENEFICIARYID = @BENEFICIARYID
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) WHERE BENEFICIARYID = @BENEFICIARYID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_DELETEEMPLOYEE]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	DELETE EMPLOYEE
-- =============================================
CREATE PROCEDURE [dbo].[SPR_DELETEEMPLOYEE]
(
	@EMPLOYEEID INT
)
AS          
SET NOCOUNT ON
BEGIN
	UPDATE EMPLOYEE SET [ISDELETED] = 1 WHERE EMPLOYEEID = @EMPLOYEEID
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) WHERE EMPLOYEEID = @EMPLOYEEID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_GETBENEFICIARIES_BY_EMPLOYEEID]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	GET BENEFICIARIES
-- =============================================
CREATE PROCEDURE [dbo].[SPR_GETBENEFICIARIES_BY_EMPLOYEEID]
(
	@EMPLOYEEID INT
)
AS          
SET NOCOUNT ON
BEGIN
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) 
	WHERE EMPLOYEEID = @EMPLOYEEID AND ISDELETED = 0
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_GETBENEFICIARY]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	GET BENEFICIARY BY BENEFICIARY ID
-- =============================================
CREATE PROCEDURE [dbo].[SPR_GETBENEFICIARY]
(
	@BENEFICIARYID INT
)
AS          
SET NOCOUNT ON
BEGIN
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) 
	WHERE BENEFICIARYID = @BENEFICIARYID AND ISDELETED = 0
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_GETEMPLOYEE]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	GET EMPLOYEE BY EMPLOYEE ID
-- =============================================
CREATE PROCEDURE [dbo].[SPR_GETEMPLOYEE]
	@EMPLOYEEID INT
AS          
SET NOCOUNT ON
BEGIN
	SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEENUMBER, CURP, SSN, PHONENUMBER, NATIONALITY, ISDELETED FROM EMPLOYEE WITH(NOLOCK)
	WHERE EMPLOYEEID=@EMPLOYEEID
	AND	ISDELETED = 0
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_GETEMPLOYEES]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	GET EMPLOYEES
-- =============================================
CREATE PROCEDURE [dbo].[SPR_GETEMPLOYEES]
AS          
SET NOCOUNT ON
BEGIN
	SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEENUMBER, CURP, SSN, PHONENUMBER, NATIONALITY, ISDELETED FROM EMPLOYEE WITH(NOLOCK)
	WHERE ISDELETED = 0
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_GETSUMBENEFICIARIES_BY_EMPLOYEEID]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	GET SUM BENEFICIARIES BY EMPLOYEE ID
-- =============================================
CREATE PROCEDURE [dbo].[SPR_GETSUMBENEFICIARIES_BY_EMPLOYEEID]
(
	@EMPLOYEEID INT
)
AS          
SET NOCOUNT ON
BEGIN
	SELECT EMPLOYEEID, SUM(PARTICIPATIONPERCENTAGE) PARTICIPATIONPERCENTAGE FROM BENEFICIARY WITH(NOLOCK) 
	WHERE EMPLOYEEID = @EMPLOYEEID AND ISDELETED = 0
	GROUP BY EMPLOYEEID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_UPDATEBENEFICIARY]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	UPDATE BENEFICIARY
-- =============================================
CREATE PROCEDURE [dbo].[SPR_UPDATEBENEFICIARY]
(
	@BENEFICIARYID INT,
	@FIRSTNAME NVARCHAR(100) ,
	@LASTNAME NVARCHAR(100) ,
	@DATEOFBIRTH DATETIME,
	@EMPLOYEEID INT,
	@CURP NVARCHAR(18),
	@SSN NVARCHAR(11) ,
	@PHONENUMBER NVARCHAR(10) ,
	@NATIONALITY NVARCHAR(50),
	@PARTICIPATIONPERCENTAGE INT
)
AS          
SET NOCOUNT ON
BEGIN
	UPDATE BENEFICIARY SET FIRSTNAME = @FIRSTNAME, LASTNAME = @LASTNAME, DATEOFBIRTH = @DATEOFBIRTH, EMPLOYEEID = @EMPLOYEEID, CURP = @CURP, SSN = @SSN, PHONENUMBER = @PHONENUMBER, NATIONALITY = @NATIONALITY, PARTICIPATIONPERCENTAGE = @PARTICIPATIONPERCENTAGE WHERE BENEFICIARYID = @BENEFICIARYID
	SELECT BENEFICIARYID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEEID, CURP, SSN, PHONENUMBER, NATIONALITY, PARTICIPATIONPERCENTAGE, ISDELETED FROM BENEFICIARY WITH(NOLOCK) WHERE BENEFICIARYID = @BENEFICIARYID
END
GO
/****** Object:  StoredProcedure [dbo].[SPR_UPDATEEMPLOYEE]    Script Date: 20/08/2023 11:41:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		MARTIN SALINAS
-- CREATE DATE: 18/08/2023
-- DESCRIPTION:	UPDATE EMPLOYEE
-- =============================================
CREATE PROCEDURE [dbo].[SPR_UPDATEEMPLOYEE]
(
	@EMPLOYEEID INT,
	@FIRSTNAME NVARCHAR(100) ,
	@LASTNAME NVARCHAR(100) ,
	@DATEOFBIRTH DATETIME,
	@EMPLOYEENUMBER INT,
	@CURP NVARCHAR(18),
	@SSN NVARCHAR(11) ,
	@PHONENUMBER NVARCHAR(10) ,
	@NATIONALITY NVARCHAR(50)
)
AS          
SET NOCOUNT ON
BEGIN
	UPDATE EMPLOYEE SET FIRSTNAME = @FIRSTNAME, LASTNAME = @LASTNAME, DATEOFBIRTH = @DATEOFBIRTH, EMPLOYEENUMBER = @EMPLOYEENUMBER, CURP = @CURP, SSN = @SSN, PHONENUMBER = @PHONENUMBER, NATIONALITY = @NATIONALITY WHERE EMPLOYEEID = @EMPLOYEEID
	SELECT EMPLOYEEID, FIRSTNAME, LASTNAME, DATEOFBIRTH, EMPLOYEENUMBER, CURP, SSN, PHONENUMBER, NATIONALITY, ISDELETED FROM EMPLOYEE WITH(NOLOCK) WHERE EMPLOYEEID = @EMPLOYEEID
END
GO